project:
  type: website
  output-dir: docs

website:
  title: "Reproducibility and Replication Teaching Modules"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Modules
        menu:
          - href: Recognizing-Reproducible-Research\recognizing_website.qmd
            text: Recognizing Reproducible and Replicable Research
          - href: Constructing-Reproduction-Documentation/organization_website.qmd
            text: Research Organization
          - href: Rotation/rotation_website.qmd
            text: Rotation Based Classroom Project
          - href: Pre-Registration\preregisration_website.qmd
            text: Pre-Regisration 
          - href: Recognizing-Reproducible-Research\recognizing_website.qmd
            text: Appraising and Assessing Dubious Research Practices
          - href: Reproducible-Code-Self-Assessment\reflection_website.qmd
            text: Reflective Assessment 

  page-footer:
    left: "© 2025 Your Name"
    right: "Built with Quarto"

format:
  html:
    page-layout: full
    toc: true
    toc-location: left
    number-sections: false
    theme:
      light: themes/rr-academic.scss
      dark: themes/rr-academic-dark.scss

include-in-header:
  - fonts.html

